server:
  port: 8089

spring:
  application:
            name: MoneyHub-Service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: syam
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect